### ISSUE TITLE
Request to consider lowercase calligraphic

### ISSUE THREAD

**Issue by apoorvpotnis** [abccsss/LeteSansMath#10]
This is a request to consider adding lowercase Latin calligraphic to the fonts, mostly for usage in category theory. Some inspiration can be found in Anthony Phan's [mathabx](https://ctan.org/pkg/mathabx) fonts, but they are serif/modulated unfortunately. The sans serified or unmodulated versions of these would be compatible with the existing uppercase calligraphic, I think. The fonts provide calligraphic digits and Greek as well.
![Screenshot 2024-11-23 132657](https://github.com/user-attachments/assets/6b5d184a-1fc9-4c2e-b644-aa0a8563be22)

**Comment by abccsss** [comment]
Marking this as closed while discussion continues in #9.
