### ISSUE TITLE
No bold version for \mathcolon

### ISSUE THREAD

**Issue by vjalby** [abccsss/LeteSansMath#5]
Hello,

Thanks for your work. I already switched to lato-math for my beamer presentation (along with Slimbach's CronosPro).

i know the bold version is not intended to be complete, but it would be great if you could add a bold version of U+2236 used by default by unicode-math for : and \mathcolon (instead of U+003A) 

Thanks !

**Comment by dflipo** [comment]
We plan to push a new version to CTAN in the next few days, we will add this glyph to the bold version.
