### ISSUE TITLE
Request: add Lato's alternate italic g

### ISSUE THREAD

**Issue by drs-p** [abccsss/LeteSansMath#6]
Hi!

Thank you for creating the LeteSansMath font, I find it really useful. I have one request: the italic Lato fonts have an alternate (single-storey) g, accessed via the salt (Stylistic Alternates) feature. Would it be possible to add this alternate glyph to LeteSansMath as well?

Thank you so much!

Best regards,
Marc

**Comment by abccsss** [comment]
Daniel added this in v0.41, and I have just updated the files [here](https://github.com/abccsss/LeteSansMath/commit/2d277872fad933bc913aac654c1e6b79c4fd0873).
