### ISSUE TITLE
Some faulty glyph constructions

### ISSUE THREAD

**Issue by EpicEricEE** [abccsss/LeteSansMath#7]
Some constructions for stretched glyphs are faulty:

- extensible right arrows and left-right arrows (single/double/triple stroked, also with hook or bar) have a gap before the right-most part
  
  ![image](https://github.com/user-attachments/assets/793cd3fd-199e-4954-bbf9-30255818a047)

- the integral symbol is missing the middle part, and has parts where the specified `overlap` is less than the `minConnectorOverlap` (not entirely sure what this means, but see https://github.com/typst/typst/pull/5288#issuecomment-2439936697 for more info)
  
  ![image](https://github.com/user-attachments/assets/156e6a21-2512-41c1-a9f7-bfef9a4d5a91)

I found these issues when using [Typst](https://github.com/typst/typst), and assume it's a font issue. If that's not the case, let me know!

**Comment by dflipo** [comment]
(I am not a Typst user).
- Regarding the arrows constructions, I see nothing wrong in the font.  F.i. the double stroked right arrow (U+21D2) is meant to be enlarged by adding one or more U+E4F2 glyphs (see the MATH table). If you try to enlarge it with the equal sign, you might encounter the gap you mention.
- The big integral is made of 'intlbottom' (U+2321), 'intextender' (U+23AE) and 'inttop'  (U+2320). All three are in the font, I just noticed wrong parameters for  'inttop'  in the MATH table, this could explain that the construction fails. We will upload a new version of LeteSansMath.otf asap, let us know if it fixes the second issue.

**Comment by dflipo** [comment]
I can also reproduce your first issue about arrows using LuaTeX. This will require some more investigations…

**Comment by abccsss** [comment]
I've uploaded a fix provided by @dflipo. Hopefully this solves the second issue!

**Comment by EpicEricEE** [comment]
Can confirm that the integral is fixed!

**Comment by abccsss** [comment]
I've updated the files again with another fix by @dflipo, and hopefully this solves the issue with extensible arrows!

**Comment by EpicEricEE** [comment]
You seem to have removed the construction for horizontal triple stroked arrows (`⇚` and `⇛`)? Other than that the issue seems fixed, so I'll close this. Thank you!

**Comment by dflipo** [comment]
Yes, I removed the construction for horizontal triple and quaduple stroked arrows as I doubt they are used by anyone…

**Comment by abccsss** [comment]
Well, I occasionally use these symbols. In higher category theory, a major branch of maths, there is the notion of [$n$-morphisms](https://ncatlab.org/nlab/show/k-morphism), which is sometimes drawn as $n$-fold arrows, a notation I particularly like, and 3-morphisms are not so rare an occurrence. In LaTeX, I've seen people overlapping a single and a double arrow to get a triple arrow. I would say at least that triple arrows are useful.

**Comment by dflipo** [comment]
Do triple or quadruple arrows really need to be extensible? The base glyphs are available in LeteSansMath.

**Comment by abccsss** [comment]
Ah, sorry, I misread your previous comment. I thought you meant removing the base glyph.

In the use case I mentioned, they do need to be extensible. There are people who use this - see [here](https://tex.stackexchange.com/q/430885) and [here](https://tex.stackexchange.com/q/537488).

But as long as the base glyph is there, I'm happy with removing the extensible versions, if fixing them turns out to be too much work.

**Comment by dflipo** [comment]
I fixed all extended arrows available with mathtools package (single stroked, double stroked, harpoons) and dropped the others. That was probably a bad decision, I will put the extended triple and quadruple arrows back in for the next version… but they will *not* be available the easy way provided by mathttools., only with raw luatex  commands like
`\[\Uoverdelimiter 0 "21DB {\hbox{\strut blablabla}}\]`
`\[\Uunderdelimiter 0 "2B45 {\hbox{\strut blablabla}}\]`
